version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bank-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12n5lakw6t81r"
s3_prefix = "bank-app"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
